micronaut:
  application:
    name: keymanagerGrpc

datasources:
  default:
    url: jdbc:mysql://localhost:3306/desafio-pix
    driverClassName: com.mysql.cj.jdbc.Driver
    username: my-user
    password: 123
    schema-generate: CREATE_DROP
    dialect: MYSQL
#jpa.default.properties.hibernate.hbm2ddl.auto: update

    jpa:
      default:
        properties:
          hibernate:
            hbm2ddl:
              auto: create-drop
            show_sql: true

    itau:
      contas:
        url: '${ITAU_URL:`http://localhost:9091/api/v1`}'

    bcb:
      pix:
        url: '${BCB_URL:`http://localhost:8082/api/v1/pix/keys`}'